# $FreeBSD: src/sys/modules/netgraph/netflow/Makefile,v 1.1.24.1.2.1 2009/10/25 01:10:29 kensmith Exp $
#
# Author: Gleb Smirnoff <glebius@freebsd.org>
#

.PATH: .

KMOD=   ng_obsr
SRCS=   ng_obsr.c

.include <bsd.kmod.mk>
