#! /bin/sh

# interfaces for LAN and WAN
LAN=em1
WAN=em0

# subnets for LAN and WAN
LAN_NET=172.20.0.0/14
WAN_NET=195.3.253.0/24


kldstat | grep dummynet >/dev/null
if [ $? -eq 0 ]
then
    echo ipfw already configured
    exit 1
fi

if [ "s$1" = "s" ]
then
   echo not screen
   screen sh $0 in_screen
   exit 0
fi


kldload dummynet
ipfw -f flush
ipfw -f table all flush

ipfw add 65530 allow ip from any to any
ipfw add 65531 allow ip6 from any to any

kldload ng_ipfw
ipfw pipe 10 config bw 10Mbit/s
ipfw add 500 skipto 510 ip from any to not table\(10\) in recv ${WAN}
ipfw add 501 pipe tablearg ip from any to table\(10\) in recv ${WAN}
ipfw add 1000 netgraph 10 ip from ${LAN_NET} to any out recv ${LAN} xmit ${WAN}
ipfw add 1100 netgraph 20 ip from any to ${WAN_NET} in recv ${WAN}
ipfw add 2000 skipto 2010 ip from not table\(20\) to any out recv ${LAN} xmit ${WAN}
ipfw add 2001 pipe tablearg ip from table\(20\) to any out recv ${LAN} xmit ${WAN}


